name=Patchugino_Analog
version=1.0.0
author=Innuvatech
maintainer=Innuvatech <andrea.rantin@Innuvatech.com>
sentence=Simple and user friendly library to use the Patchugino PT100 shield board
paragraph=For easy and immediate developement
category=Device Control
url=https://github.com/Innuvatech/Patchugino_Analog
architectures=*
includes=patchugino_analog.h
depends=Patchugo_Core